### ISSUE TITLE
error in stage 2

### ISSUE THREAD

**Issue by Swarau** [bcalden/ClusterPyXT#35]
Dear Sir,

I tried to run the code. I have created the source and exclude regions. I have proceeded further through GUI mode as well as command line mode (python clusterpyxt.py --continue)
When I clicked on run stage 2, I have encountered with the following error. I am unable to resolve it. 
It will be very useful, I you could provide one example. 

Traceback (most recent call last):
  File "clusterpyxt.py", line 533, in run_stage_2
    ciao.run_stage_2_parallel(self._cluster_obj, get_arguments())
  File "/home/sk/ClusterPyXT-master/ciao.py", line 1357, in run_stage_2_parallel
    remove_sources_in_parallel(cluster,args)
  File "/home/sk/ClusterPyXT-master/ciao.py", line 671, in remove_sources_in_parallel
    with mp.Pool(args.num_cpus) as pool:
  File "/home/sk/CIAO/ciao-4.14/ots/lib/python3.8/multiprocessing/context.py", line 119, in Pool
    return Pool(processes, initializer, initargs, maxtasksperchild,
  File "/home/sk/CIAO/ciao-4.14/ots/lib/python3.8/multiprocessing/pool.py", line 205, in __init__
    raise ValueError("Number of processes must be at least 1")
ValueError: Number of processes must be at least 1
Aborted (core dumped)

**Comment by bcalden** [comment]
While I work on a fix, can you tell me the results of the following command (run from your ciao environment):

`python -c 'import multiprocessing as mp; print(mp.cpu_count())'`

**Comment by Swarau** [comment]
Dear Sir,

This is the output of the following command:

python -c 'import multiprocessing as mp; print(mp.cpu_count())'

4

**Comment by bcalden** [comment]
If you get the latest release of the master branch, this issue should be fixed, if not, please advise.  A simple `git pull` in the ClusterPyXT directory should do the trick.
